spring.application.name: admin-service
spring.profiles.active: dev

server:
  port: 8082

spring:
  elasticsearch:
    uris: ${ES_URIS}
    connection-timeout: 5s
    socket-timeout: 3s

  datasource:
    url: ${STORAGE_DB_URL}
    username: ${STORAGE_DB_USER}
    password: ${STORAGE_DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver

  batch:
    jdbc:
      initialize-schema: always

    job:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: prometheus

queue:
  product:
    max-capacity: 10000
