name: CD

on:
  push:
    branches:
      - 'main'
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'gradle'

      - name: Grant execute permission for gradle
        run: chmod +x ./gradlew

      - name: create build file
        run: ./gradlew clean build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: core/core-api/build/libs/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name : Download a built Jar File
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build/libs

      - name: Transfer JAR to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          source: build/libs/*.jar
          target: "/home/ubuntu/"

      - name: Transfer Deploy.sh to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          source: deploy.sh
          target: "/home/ubuntu/"

      - name: Restart application on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          script: |
            chmod +x /home/ubuntu/deploy.sh
            bash -c "nohup /home/ubuntu/deploy.sh > /dev/null 2>&1 &"